name: zeus
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.3
  cloud_firestore: ^4.17.5
  image_picker: ^1.0.4
  fl_chart: ^0.63.0
  table_calendar: ^3.0.10
  google_fonts: ^6.2.0
  intl: 0.20.2
  csv: ^5.0.2
  path_provider: ^2.1.2
  font_awesome_flutter: ^10.8.0
  iconly: ^1.0.1
  flutter_animate: ^4.5.0
  qr_flutter: ^4.0.0
  qr_code_scanner: ^1.0.1
  video_player: ^2.8.0
  flutter_launcher_icons: ^0.13.1
  chewie: 1.7.1
  mailer: ^6.1.3
  google_generative_ai: ^0.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/videos/plank.mp4
    - assets/videos/crunches.mp4
    - assets/videos/push_up.mp4
    - assets/videos/bench_press.mp4
    - assets/videos/yoga.mp4
    - assets/videos/jumping_jacks.mp4
    - assets/videos/squat.mp4
    - assets/videos/lunge.mp4
    - assets/videos/bicep_curl.mp4
    - assets/videos/cable_flyes.mp4
    - assets/videos/warm_up.mp4
    - assets/videos/fullbody.mp4
    - assets/videos/lowerbody.mp4
    - assets/videos/abworkout.mp4
    - assets/videos/workout.mp4
    - assets/videos/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"